### ISSUE TITLE
google-services.json is missing

### ISSUE THREAD

**Issue by SaeedYounus1996** [aubykhan/flutter_pk#2]
The code is not running without google-services.json
here is the log

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugGoogleServices'.
> > File google-services.json is missing. The Google Services Plugin cannot function without it. 
>    Searched Location: 
>   D:\uni_projects\flutter\flutter_pk\flutter_pk\android\app\src\nullnull\debug\google-services.json
>   D:\uni_projects\flutter\flutter_pk\flutter_pk\android\app\src\debug\nullnull\google-services.json
>   D:\uni_projects\flutter\flutter_pk\flutter_pk\android\app\src\nullnull\google-services.json
>   D:\uni_projects\flutter\flutter_pk\flutter_pk\android\app\src\debug\google-services.json
>   D:\uni_projects\flutter\flutter_pk\flutter_pk\android\app\src\nullnullDebug\google-services.json
>   D:\uni_projects\flutter\flutter_pk\flutter_pk\android\app\google-services.json
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 45s
> Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by kamrancr7** [comment]
generate that file from the following link 
https://firebase.google.com/
and paste it in the app level directory of your project.

**Comment by aubykhan** [comment]
You normally don't upload keys to repos. Just like @kamrancr7 says, you'll need to generate and use your own from Firebase.

Closing this one.
